---
  - name: "Installing tomcat for {{ page_title }}"
    include_role:
      name: tomcat

  - name: Configuring {{ page_title }} context
    template: 
      src: context.xml.j2
      dest: "{{ catalina_home }}/conf/context.xml"
  
  - name: Remove default ROOT directory
    file:
      path: "{{ catalina_home }}/webapps/ROOT"
      state: absent
  
  - name: Download WAR
    get_url:
      url: "https://s3-us-west-2.amazonaws.com/cto-playground/employee_app.war"
      dest: "{{ catalina_home }}/webapps/ROOT.war"
  
  - name: "restart {{ service_name }}"
    service: name="{{ service_name }}" state=restarted
