version: '3'
services:
  tcw:
    build:
      context: .
      dockerfile: demo-workshops/tcw/image-builder/Dockerfile
      args:
        DEMO_PATH: demo-workshops
        DEMO_NAME: tcw
    user: ${CURRENT_UID}
    volumes:
      - .:/build
    env_file: .docker.env 