#The new password you want for guacadmin
guacadmin_password: changeme

#The username of the guacuser
guac_user: delphix

#The password of the guacuser
guac_user_password: changeme

#The password used to configure VNC
vnc_password: changeme