---
  - name: Install Desktop tools
    apt:
      name: "{{ packages }}"
      state: present
    become: True
    vars:
      packages:
        - putty
        - remmina
  - name: Install google-chrome-stable
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      state: present
    become: True
  - name: Create Chrome shortcut
    copy: src=delphix-engine.desktop dest=/home/ubuntu/Desktop/delphix-engine.desktop mode="u+x,g+x"
  - name: Create Putty shortcut
    copy: src=putty.desktop dest=/home/ubuntu/Desktop/putty.desktop mode="u+x,g+x"
  - name: Create RDP shortcut
    copy: src=rdp.desktop dest=/home/ubuntu/Desktop/rdp.desktop mode="u+x,g+x"
  - name: Create eclipse icon
    copy: src=icon.xpm dest=/home/ubuntu/icon.xpm mode="u+x,g+x"
  - name: Create eclipse shortcut
    copy: src=eclipse.desktop dest=/home/ubuntu/Desktop/eclipse.desktop mode="u+x,g+x"
  - name: Create config sql
    template: 
      src: guac_settings_import.sql.j2
      dest: "/tmp/guac_settings_import.sql"
  - name: Setup Guacamole users, passwords, and connections
    become: True
    mysql_db:
      name: guacamole
      state: import
      target: /tmp/guac_settings_import.sql
  - name: Extract xfce settings
    unarchive:
      src: xfce_config.tgz
      dest: /home/ubuntu