---
  - name: All the tools playbook
    hosts: all
    become: yes
    vars:
      java_packages:
        - java-1.8.0
      jenkins_plugins: # have to list all dependencies due to https://github.com/ansible/ansible/issues/24864
        - workflow-support
        - credentials
        - structs
        - git-server
        - aws-credentials
        - aws-java-sdk
        - purge-job-history
        - jdk-tool
        - workflow-cps-global-lib
        - script-security
        - branch-api
        - command-launcher
        - jackson2-api
        - apache-httpcomponents-client-4-api
        - workflow-multibranch
        - bouncycastle-api
        - workflow-aggregator
        - ssh-credentials
        - workflow-step-api
        - plain-credentials
        - workflow-scm-step
        - jsch
        - git-client
        - scm-api
        - display-url-api
        - mailer
        - workflow-api
        - junit
        - matrix-project
        - git
        - pipeline-model-extensions
        - pipeline-milestone-step
        - jquery-detached
        - ace-editor
        - workflow-cps
        - pipeline-input-step
        - pipeline-stage-step
        - workflow-job
        - cloudbees-folder
        - pipeline-graph-analysis
        - pipeline-rest-api
        - handlebars
        - momentjs
        - pipeline-stage-view
        - pipeline-build-step
        - pipeline-model-declarative-agent
        - authentication-tokens
        - docker-commons
        - durable-task
        - pipeline-model-definition
        - workflow-durable-task-step
        - workflow-basic-steps
        - docker-workflow
        - lockable-resources
        - pipeline-stage-tags-metadata
        - blueocean-rest
        - credentials-binding
        - pipeline-model-api
        - github
        - jenkins-design-language
        - blueocean-core-js
        - github-api
        - token-macro
        - github-branch-source
        - blueocean-commons
        - pubsub-light
        - blueocean-pipeline-scm-api
        - htmlpublisher
        - variant
        - blueocean-web
        - blueocean-jwt
        - favorite
        - blueocean-rest-impl
        - blueocean-pipeline-api-impl
        - blueocean-github-pipeline
        - blueocean-git-pipeline
        - blueocean-config
        - mercurial
        - handy-uri-templates-2-api
        - cloudbees-bitbucket-branch-source
        - blueocean-bitbucket-pipeline
        - blueocean-dashboard
        - blueocean-personalization
        - jira
        - blueocean-jira
        - blueocean-display-url
        - sse-gateway
        - blueocean-events
        - blueocean-pipeline-editor
        - blueocean-i18n
        - blueocean-autofavorite
        - blueocean
        - blueocean-executor-info
      jenkins_java_options: '-Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP=\"script-src ''unsafe-inline'';\"'
      jenkins_plugins_state: latest # have to use 'latest' https://github.com/geerlingguy/ansible-role-jenkins/issues/234
      git_packages:
        - git
      nodejs_version: "10.x"
      nodejs_npm_global_packages:
        - '@angular/cli'
        - '@angular-devkit/build-angular'
    roles:
      - role: geerlingguy.java
      - role: geerlingguy.jenkins
      - role: geerlingguy.docker
      - role: geerlingguy.git
      - role: geerlingguy.nodejs
      - role: ocha.yarn
