---
- name: Setup nginx
  include_role:
    name: geerlingguy.nginx
- name: Configure NGINX
  template: 
    src: nginx.conf.d.j2
    dest: "/etc/nginx/conf.d/default.conf"
- name: Restart nginx
  service: name=nginx state=restarted
- name: Firewall
  include_role:
    name: geerlingguy.firewall