---
- name: Create the app_repo directory
  file:
    path: /var/lib/jenkins/app_repo.git
    state: directory
    mode: "u+rwx,g+rwx"
    owner: centos
    group: centos
  register: app_repo
  tags:
    - git
- name: Set permissions on the app_repo.git
  shell: |
    find app_repo.git -type d -exec chmod g+s '{}' +
    chown -R centos.jenkins app_repo.git
    chmod -R g+rwX app_repo.git
  args:
      chdir: /var/lib/jenkins
  become: true
- name: Init app_repo directory as a bare git repo
  shell: |
    git init --bare /var/lib/jenkins/app_repo.git
  args:
    creates: /var/lib/jenkins/app_repo.git/.git
  become: no
  when: "app_repo.changed"
  tags:
    - git
- name: Clone the app_repo source
  git:
    dest: /tmp/app_repo_source
    repo: https://github.com/delphix/automation-framework-demo.git
    version: demos/tcw
  retries: 3
  delay: 2
  become: no
  tags:
    - git
#Get a weird error using the git module for this due to it being an empty repo
- name: Clone the bare app_repo
  shell: |
    git clone /var/lib/jenkins/app_repo.git
  args:
     chdir: /tmp
     creates: /tmp/app_repo
  retries: 3
  delay: 2
  become: no
  tags:
    - git
- name: Populate the repo
  synchronize:
    src: /tmp/app_repo_source/
    dest: /tmp/app_repo
    rsync_opts:
      - "--exclude=.git"
  delegate_to: "{{ inventory_hostname }}"
  become: no
  tags:
    - git
- name: Are there things to add to git?
  shell: |
    git status
  args:
    chdir: /tmp/app_repo
  register: git_status
  changed_when: false
  tags:
    - git
- name: Commit and push the master, production, and develop branch
  shell: |
    git add -A
    git commit -m "init"
    git push origin master
    git checkout -b production
    git push origin production
    git checkout -b develop
    git push origin develop
  args:
    chdir: /tmp/app_repo
  become: no
  when: "'git add' in git_status.stdout"
  tags:
    - git
- name: Place hook
  copy: 
    src: post-update
    dest: "/var/lib/jenkins/app_repo.git/hooks/post-update"
    mode: "a+x"
  become: no
  tags:
    - git
- name: Get last abbreviated git hash
  shell: |
    git checkout develop &>> /dev/null
    git rev-parse --short HEAD
  args:
    chdir: /tmp/app_repo
  register: gitlog
  become: no
  changed_when: false
  tags:
    - datical
- debug:
    msg: "{{gitlog.stdout}}"
  tags:
    - datical
- name: tar up app_repo for restore
  shell: | 
    tar cvzf app_repo.tgz app_repo.git
  args:
    chdir: /var/lib/jenkins
  become: yes
- name: Yarn install
  shell: |
    yarn install
  args:
    chdir: /tmp/app_repo/client
  register: yarn_out
  changed_when: "'Already up-to-date' not in yarn_out.stdout"