---
  - name: Updating .bash_profile
    blockinfile:
      path: "/home/{{ delphix_user }}/.bash_profile"
      state: present
      block: |
        export ORACLE_HOME={{ oracle_home }}
        export ORACLE_BASE={{ oracle_base }}
        export PATH=$ORACLE_HOME/bin:$ORACLE_HOME/bin:$ORACLE_HOME/OPatch:$PATH
  - name: "Add {{ delphix_user }} user to oracle groups"
    user:
      name: "{{ delphix_user }}"
      shell: /bin/bash
      group: "{{ oracle_inventory_group }}"
      groups: 
        - "{{ osdba_group }}"
        - "{{ delphix_group }}"
      append: yes
  - name: "Update {{ oracle_home }}/dbs perms"
    file:
      path: "{{ oracle_home }}/dbs"
      mode: g+rwx
  - name: "Update {{ oracle_home }}/bin/oracle perms"
    file:
      path: "{{ oracle_home }}/bin/oracle"
      mode: 06751
  - name: "Set pam soft nofile limit for {{ delphix_user }}"
    pam_limits:
      domain: "{{ delphix_user }}"
      limit_type: soft
      limit_item: nofile
      value: 1024
  - name: "Set pam hard nofile limit for {{ delphix_user }}"
    pam_limits:
      domain: "{{ delphix_user }}"
      limit_type: hard
      limit_item: nofile
      value: 65536
  - name: "Set pam nproc limit for {{ delphix_user }}"
    pam_limits:
      domain: "{{ delphix_user }}"
      limit_type: '-'
      limit_item: nproc
      value: 16384
  - name: "Set pam soft stack limit for {{ delphix_user }}"
    pam_limits:
      domain: "{{ delphix_user }}"
      limit_type: soft
      limit_item: stack
      value: 10240
  - name: "Set pam hard stack limit for {{ delphix_user }}"
    pam_limits:
      domain: "{{ delphix_user }}"
      limit_type: hard
      limit_item: stack
      value: 32768
  - name: "Set pam memlock limit for {{ delphix_user }}"
    pam_limits:
      domain: "{{ delphix_user }}"
      limit_type: '-'
      limit_item: memlock
      value: 134217728
  - name: Set net.ipv4.tcp_rmem to 16777216
    sysctl:
      name: net.ipv4.tcp_rmem
      value: '16777216 16777216 16777216'
      sysctl_set: yes
      state: present
      reload: yes
  - name: Set net.ipv4.tcp_wmem to 4194304
    sysctl:
      name: net.ipv4.tcp_wmem
      value: '16777216 16777216 16777216'
      sysctl_set: yes
      state: present
      reload: yes
  - name: create the toolkit directory
    file:
      mode: 0770
      path: "{{ toolkit_dir }}"
      state: directory
      group: "{{ oracle_inventory_group }}"
      owner: "{{ delphix_user }}"
  - name: create the mnt directory
    file:
      mode: 0770
      path: "{{ delphix_mount }}"
      state: directory
      group: "{{ oracle_inventory_group }}"
      owner: "{{ delphix_user }}"