---
  - name: DAF Webapp playbook
    hosts: all
    become: yes
    vars:
      java_packages:
        - java-1.8.0-openjdk
    roles:
      - role: geerlingguy.java
      - role: daf-webapp-toolchain

