---

- name: install oracle
  hosts: "all"
  become: yes
  become_method: sudo
  roles:
    - delphix.target-host
    - oracle_install
    - delphix_oracle
    - geerlingguy.firewall
  vars:
    oracle_pv: /dev/xvdb
    oracle_installer_path: /tmp
    oracle_pass: delphixdb
    oracle_db_syspass: delphixdb
    oracle_hostname: "{{ ansible_hostname }}"
    oracle_edition: EE
    oracle_db_home: ora_1
    oracle_version: 11.2.0.4
    oracle_base: /u01/app/oracle
    oracle_home: "{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}"
    oracle_bin_fs: "{{ oracle_base }}"
    install_mode: INSTALL_DB_SWONLY
    toolkit_dir: /u01/app/toolkit
    firewall_allowed_tcp_ports:
      - "22"
      - "1521"
