---
  service_name: "tomcat"
  catalina_home: "/usr/share/tomcat"
  db_host: localhost
  db_port: 1521
  db_sid: rdsrepl
  db_user: delphixdb
  db_password: delphixdb
  page_title: "change me"
  read_only: "false"